START OF DATA
TIME OF DATA 2019 1 19 2 0 53 
POSITION 49 40 0 
HPL 17.4272
VPL
ELEVATION MASK 0
TYPE OF PL CALCULATION UNKNOWN
PROBABILITY OF INTEGRITY 0.99
HP ERROR
VP ERROR
POSITION ERROR
HORIZONTAL ALARM LIMIT
VERTICAL ALARM LIMIT
ALARM LIMIT 3D
START OF COV MATRIX ECEF
44.431 -6.74544 13.1391
-6.74544 7.45801 1.16093
13.1391 1.16093 11.3437
END OF COV MATRIX ECEF
START OF COV MATRIX ENU
29.3773 9.66662 -18.4153
9.66662 6.9987 -7.03432
-18.4153 -7.03432 26.8567
END OF COV MATRIX ENU
START OF USED SAT
0 8 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 10 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 11 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 14 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 16 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 18 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 20 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 27 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 32 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
END OF USED SAT
START OF UNUSED SAT
0 15 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 21 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 24 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
END OF UNUSED SAT
END OF DATA
START OF DATA
TIME OF DATA 2019 1 19 2 0 53 
POSITION 49 40 0 
HPL 17.4272
VPL
ELEVATION MASK 0
TYPE OF PL CALCULATION UNKNOWN
PROBABILITY OF INTEGRITY 0.99
HP ERROR
VP ERROR
POSITION ERROR
HORIZONTAL ALARM LIMIT
VERTICAL ALARM LIMIT
ALARM LIMIT 3D
START OF COV MATRIX ECEF
44.431 -6.74544 13.1391
-6.74544 7.45801 1.16093
13.1391 1.16093 11.3437
END OF COV MATRIX ECEF
START OF COV MATRIX ENU
29.3773 9.66662 -18.4153
9.66662 6.9987 -7.03432
-18.4153 -7.03432 26.8567
END OF COV MATRIX ENU
START OF USED SAT
0 8 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 10 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 11 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 14 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 16 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 18 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 20 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 27 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 32 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
END OF USED SAT
START OF UNUSED SAT
0 15 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 21 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
0 24 el UNKNOWN az UNKNOWN IPP lat UNKNOWN IPP lon UNKNOWN Iono Delay [m] UNKNOWN Iono RMS [m] UNKNOWN 
END OF UNUSED SAT
END OF DATA
