function Stanford_Plot(pl_file)

    [filepath,name,ext] = fileparts(pl_file);

    out_name = strrep(name,'.','_');

    A = importdata(pl_file);

    pparam = setPlotParameters( filepath );

    plData = A(:,1);
    errorData = A(:,3);
    numberOfSat = A(:,7);
    strRequirementName = 'PL Horizontal (3 \sigma)';
    AlertLimit_m = 5;

    createStanfordDiagram(	abs(errorData) ...
                            ,plData ...
                            ,25 ...
                            ,numberOfSat ...
                            ,AlertLimit_m ...
                            ,strRequirementName ...
                            ,'Number of Used Sat' ...
                            ,strcat(filepath,'\Stanford_Diagram_','PL Horizontal_',out_name) ...
                            ,pparam);

    plData = A(:,2);
    errorData = A(:,4);
    numberOfSat = A(:,7);
    strRequirementName = 'PL Vertical (3 \sigma)';
    AlertLimit_m = 7;

    createStanfordDiagram(	abs(errorData) ...
                            ,plData ...
                            ,25 ...
                            ,numberOfSat ...
                            ,AlertLimit_m ...
                            ,strRequirementName ...
                            ,'Number of Used Sat' ...
                            ,strcat(filepath,'\Stanford_Diagram_','PL Vertical_',out_name) ...
                            ,pparam);                    

end
